### ISSUE TITLE
 too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by bibekananda-pradhan** [mathpseudo/helmet-detector#2]
i am new to python , just downloaded your code and tried executing got this error , guide me to resolve it.
```
Traceback (most recent call last):
  File "E:\f drive back up\Project\MachineLearningOpenHack\helmet-detector-master\helmet_pattern_detection.py", line 79, in <module>
    pattern_detection(1)
  File "E:\f drive back up\Project\MachineLearningOpenHack\helmet-detector-master\helmet_pattern_detection.py", line 48, in pattern_detection
    contours,h=cv2.findContours(edge_image,1,2)
ValueError: too many values to unpack (expected 2)
```

**Comment by mathpseudo** [comment]
Which version are you using? I used Python 2.7.8 for this IIRC. This error may be arising due to not providing an image file.

**Comment by sivaparvathi555** [comment]
Hi,

Traceback (most recent call last):
  File "helmet_pattern_detection.py", line 79, in <module>
    pattern_detection(1)
  File "helmet_pattern_detection.py", line 64, in pattern_detection
    c=count_transitions(frame,min_x,min_y,max_x,max_y)/3
  File "helmet_pattern_detection.py", line 31, in count_transitions
    if(abs(int(image[i,mid_y][0]-image[i+1,mid_y][0]))>=200):
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices


 I am getting this error..Please resolve as soon as possibile

**Comment by Himabindu28** [comment]
> Hi,
> 
> Traceback (most recent call last):
> File "helmet_pattern_detection.py", line 79, in
> pattern_detection(1)
> File "helmet_pattern_detection.py", line 64, in pattern_detection
> c=count_transitions(frame,min_x,min_y,max_x,max_y)/3
> File "helmet_pattern_detection.py", line 31, in count_transitions
> if(abs(int(image[i,mid_y][0]-image[i+1,mid_y][0]))>=200):
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
> 
> I am getting this error..Please resolve as soon as possibile

I am also getting the same error @mathpseudo please resolve
